# Generated by Django 6.0.1 on 2026-02-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_message", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="message_attachment/",
                verbose_name="Вложение",
            ),
        ),
    ]
